import '../styles/globals.css'
import { Navigation } from '../components/Navigation'

export const metadata = {
  title: 'Mi primera app Next.js',
  description: 'Generated by Next.js'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='es'>
      <head>
        <title>{metadata.title}</title>
      </head>
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  )
}
